#!/bin/sh

# Set VWRT home directory
uci set uhttpd.main.home='/www/vwrt'
uci commit uhttpd

# Create symlinks for LuCI
ln -sf /www/luci-static /www/vwrt/luci-static
ln -sf /www/cgi-bin/luci /www/vwrt/cgi-bin/luci

# Create VWRT backup instance on Port 2222 if not exists
if ! uci get uhttpd.vwrt >/dev/null 2>&1; then
    uci set uhttpd.vwrt=uhttpd
    uci add_list uhttpd.vwrt.listen_http='0.0.0.0:2222'
    uci add_list uhttpd.vwrt.listen_http='[::]:2222'
    uci set uhttpd.vwrt.home='/www/vwrt'
    uci set uhttpd.vwrt.cgi_prefix='/cgi-bin'
    uci commit uhttpd
fi

# Enable and Start internet-detector
if [ -f "/etc/init.d/internet-detector" ]; then
    /etc/init.d/internet-detector enable
    /etc/init.d/internet-detector start
fi

# Configure Default WiFi Settings (Dynamic Detection)
# Iterate through all wifi-devices to configure Radio settings
for radio in $(uci show wireless | grep "=wifi-device" | cut -d'.' -f2 | cut -d'=' -f1); do
    band=$(uci -q get wireless.$radio.band)
    
    # Common settings for High Performance
    uci set wireless.$radio.country='US'
    uci set wireless.$radio.txpower='100'
    uci set wireless.$radio.mu_beamformer='1'

    if [ "$band" = "5g" ]; then
        # 5GHz: VWRT_5G, HE160, CH149, 11a (AX base)
        uci set wireless.$radio.hwmode='11a'
        uci set wireless.$radio.channel='149'
        uci set wireless.$radio.htmode='HE160'
    elif [ "$band" = "2g" ]; then
        # 2.4GHz: VWRT_2.4G, HE40, Auto, 11g (AX base), Force 40MHz
        uci set wireless.$radio.hwmode='11g'
        uci set wireless.$radio.channel='auto'
        uci set wireless.$radio.htmode='HE40'
        uci set wireless.$radio.noscan='1' # Force 40MHz width
    fi
done

# Iterate through all wifi-interfaces to set SSIDs based on attached device band
for iface in $(uci show wireless | grep "=wifi-iface" | cut -d'.' -f2 | cut -d'=' -f1); do
    device=$(uci -q get wireless.$iface.device)
    band=$(uci -q get wireless.$device.band)

    uci set wireless.$iface.encryption='none'
    
    if [ "$band" = "5g" ]; then
        uci set wireless.$iface.ssid='VWRT_5G'
    elif [ "$band" = "2g" ]; then
        uci set wireless.$iface.ssid='VWRT_2.4G'
    fi
done

# Commit changes
uci commit wireless
wifi reload

exit 0
