#!/bin/sh
# VWRT Services Auto-Enable Script
# This runs once on first boot or after factory reset

/etc/init.d/mobile_poller enable
/etc/init.d/sms_sync enable
/etc/init.d/vwrt_watchdog enable


exit 0
