#!/bin/sh /etc/rc.common
# VWRT Connectivity Watchdog Service
# Copyright (C) 2026 VWRT

START=99
USE_PROCD=1
PROG=/www/vwrt/services/mm_watchdog.sh

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "$PROG"
    
    # Auto-restart if the script crashes or is killed
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    
    # Output logs to system log
    procd_set_param stdout 1
    procd_set_param stderr 1
    
    procd_close_instance
}

stop_service() {
    # Procd handles stopping automatically
    return 0
}
